restartpolicy: "Never"
timeoutcreate: 1m30s
timeoutdelete: 1m30s
namespace: sciencedata-dev
tokendir: /tmp/tokens
publicip: "130.226.137.130"
whitelistmanifestregex: https:\/\/raw[.]githubusercontent[.]com\/deic-dk\/pod_manifests
tokenbytelimit: 4096
nfsstorageroot: "/tank/storage"
testinghost: "10.0.0.20"
