defaultRestartPolicy: "Never"
timeoutCreate: 1m30s
timeoutDelete: 1m30s
namespace: sciencedata-dev
podCacheDir: /tmp/podcaches
whitelistmanifestregex: https:\/\/raw[.]githubusercontent[.]com\/deic-dk\/pod_manifests
tokenbytelimit: 4096
nfsStorageRoot: "/tank/storage"
testingHost: "10.0.0.20"
localRegistryURL: ""
localRegistrySecret: "docker-registry-auth"
ingressDomain: ""
ingressWildcardSecret: "user-pods-wildcard"
podSubnetCidr: "10.128.0.0/15"
testSshKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFFaL0dy3Dq4DA5GCqFBKVWZntBSF0RIeVd9/qdhIj2n joshua@myhost"
testUser: "registeredtest7"
hostnameList:
  - hostname: silo7.sciencedata.dk
    address: 10.0.0.20
  - hostname: silo1.sciencedata.dk
    address: 10.0.0.14
