defaultRestartPolicy: "Never"
timeoutCreate: 1m30s
timeoutDelete: 1m30s
namespace: sciencedata-dev
podCacheDir: /tmp/podcaches
whitelistmanifestregex: https:\/\/raw[.]githubusercontent[.]com\/deic-dk\/pod_manifests
tokenbytelimit: 4096
nfsStorageRoot: "/tank/storage"
testingHost: "10.0.0.20"
localRegistryURL: ""
localRegistrySecret: "docker-registry-auth"
ingressDomain: ""
ingressIssuer: "user-pods-issuer"
ingressWildcardSecret: "user-pods-wildcard"
