apiVersion: v1
kind: Namespace
metadata:
  name: sciencedata-dev
  labels:
    name: sciencedata-dev

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-pods-backend
  namespace: sciencedata-dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-sciencedata
  namespace: sciencedata-dev
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - delete 
      - create
      - watch
  - apiGroups: [""]
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - list
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-sciencedata-to-sa
  namespace: sciencedata-dev
subjects:
  - kind: ServiceAccount
    name: user-pods-backend
roleRef:
  kind: Role
  name: modify-sciencedata 
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provision-nfs
rules:
  - apiGroups: [""]
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - delete 
      - create
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provision-nfs-to-sa
subjects:
  - kind: ServiceAccount
    name: user-pods-backend
    namespace: sciencedata-dev
roleRef:
  kind: ClusterRole
  name: provision-nfs
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata: 
  name: user-pods-backend-testing
  namespace: sciencedata-dev
  labels:
    app: user-pods-backend-testing
spec:
  serviceAccountName: user-pods-backend
  imagePullSecrets:
    - name: docker-registry-auth
  containers:
    - name: user-pods-backend-testing
      image: dockerregistry.clement.tel/kubernetes_backend
      env:
        - name: "SSH_PUBLIC_KEY"
          value: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFFaL0dy3Dq4DA5GCqFBKVWZntBSF0RIeVd9/qdhIj2n"
        - name: "BACKEND_PUBLICIP"
          value: "130.226.137.135"
        - name: "BACKEND_LOCALREGISTRYURL"
          value: "dockerregistry.clement.tel"
        - name: "BACKEND_LOCALREGISTRYSECRET"
          value: "docker-registry-auth"
        - name: "BACKEND_INGRESSURL"
          value: "testk8s.clement.tel"
      ports:
        - containerPort: 22
          protocol: TCP
        - containerPort: 80
          protocol: TCP
      securityContext:
        capabilities:
          add:
            - "SYS_CHROOT"
            - "AUDIT_WRITE"
---
apiVersion: v1
kind: Service
metadata:
  name: user-pods-backend-testing-ssh
  namespace: sciencedata-dev
spec:
  type: NodePort
  ports:
    - port: 22
      targetPort: 22
      name: ssh
      protocol: TCP
      nodePort: 30002
  selector:
    app: user-pods-backend-testing
