apiVersion: v1
kind: ServiceAccount
metadata:
        name: user-pods-backend

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
        name: modify-pods
rules:
        - apiGroups: [""]
          resources:
                  - pods
          verbs:
                  - get
                  - list
                  - delete 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
        name: modify-pods-to-sa
subjects:
        - kind: ServiceAccount
          name: user-pods-backend
roleRef:
        kind: Role
        name: modify-pods
        apiGroup: rbac.authorization.k8s.io

